### ISSUE TITLE
Install for `next` fails

### ISSUE THREAD

**Issue by sumeshir26** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#589]
![image](https://user-images.githubusercontent.com/68823982/143844368-9b1d854b-6539-4f40-94fe-163f1ef8fde1.png)

**Comment by Melvin-Abraham** [comment]
@sumeshir26 I have added build instructions for development on the `next` branch. If that doesn't work, let me know...

**Comment by im-coder-lg** [comment]
Saw this on my notification feed and checked it out. I think it might be just me since I ended up with these problems:
Console log(added space on the log commands like the concurrently command, yarn compile, vite, etc:
```console
$ yarn dev
yarn run v1.22.17
 $ concurrently "yarn watch:renderer" "yarn watch:main"
 $ yarn compile:main --watch --preserveWatchOutput
 $ vite
 $ ttsc -p ./src/main/tsconfig.json --watch --preserveWatchOutput
[1]
[1] 7:12:18 PM - Starting compilation in watch mode...
[1]
[0] Pre-bundling dependencies:
[0]   react
[0]   react-dom
[0]   react/jsx-dev-runtime
[0] (this will be run only when your dependencies or config have changed)
[0]
[0]   vite v2.6.13 dev server running at:
[0]
[0]   > Local: http://localhost:3000/
[0]   > Network: use `--host` to expose
[0]
[0]   ready in 5292ms.
[0]
[1]
[1] 7:12:33 PM - Found 0 errors. Watching for file changes.
[0]
[0] Found 0 errors. Watching for file changes.
[0] Sourcemap for "D:/GitHub/not_mine/GAUDC-next/node_modules/.vite/react.js" points to missing source files
[0] Sourcemap for "D:/GitHub/not_mine/GAUDC-next/node_modules/.vite/react_jsx-dev-runtime.js" points to missing source files
[0] [BABEL] Note: The code generator has deoptimised the styling of D:\GitHub\not_mine\GAUDC-next\node_modules\.vite\react-dom.js?v=5a520f53 as it exceeds the max of 500KB.
[0] Sourcemap for "D:/GitHub/not_mine/GAUDC-next/node_modules/.vite/react-dom.js"
points to missing source files
```
Recording:
recording will be posted soon here, need to edit personal things.

So, since the branch is in development, it's a web server, right?
And after 2.0.0's beta is released, the electron version will be activated, right?
PS: This is almost 10 hours old, forgot to post it.

**Comment by sumeshir26** [comment]
@Melvin-Abraham No, I get this error😕
![image](https://user-images.githubusercontent.com/68823982/143980304-9bd60f38-5b0d-42d6-8481-56c202116e07.png)

**Comment by Melvin-Abraham** [comment]
> @Melvin-Abraham No, I get this error😕 ![image](https://user-images.githubusercontent.com/68823982/143980304-9bd60f38-5b0d-42d6-8481-56c202116e07.png)

@sumeshir26 This was the same reason why the build failed on the CI but I'm unsure why this is failing. Although, I would suggest pulling the latest commits as the code in this screenshot seems to be from an older commit. Once on the latest commit, you probably won't get this error.

**Comment by Melvin-Abraham** [comment]
@im-coder-lg

> I think it might be just me since I ended up with these problems

The server seems to be running as it should. The other messages that you are seeing at the bottom of the logs are just warnings for now. The following line from your log confirms that there are no errors:

```
7:12:33 PM - Found 0 errors. Watching for file changes.

Found 0 errors. Watching for file changes
```

> So, since the branch is in development, it's a web server, right?
> And after 2.0.0's beta is released, the electron version will be activated, right?

Actually, you will have to run two commands as per the build instructions given in [this discussion](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/discussions/576). One being `yarn dev` which will start a dev server for compilation and the other being `yarn start` for starting the electron application. In any case, try and see if you are able to launch the app.

**Comment by im-coder-lg** [comment]
Check these logs when I ran `yarn start`:
```console
$ yarn start
yarn run v1.22.17
 $ electron .
 $pathtogaudc\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath ($pathtogaudc\node_modules\electron\index.js:14:11)
    at Object.<anonymous> ($pathtogaudc\node_modules\electron\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> ($pathtogaudc\node_modules\electron\cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

$ electron .

App threw an error during load
 $pathtogaudc\out\main\app.js:4
const process = require("process");
                                 ^
SyntaxError: Identifier 'process' has already been declared
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at loadApplicationPackage (C:\Users\DELL\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\resources\default_app.asar\main.js:280:12)
    at Object.<anonymous> (C:\Users\DELL\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\resources\default_app.asar\main.js:322:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)

$ git status
On branch next
Your branch is up to date with 'origin/next'.

nothing to commit, working tree clean
```
Deleted and reinstalled the modules but I still fail.

**Comment by Melvin-Abraham** [comment]
@im-coder-lg Try running the following command from the project root in your terminal:

```console
$ node ./node_modules/electron/install.js
```

After the above command is done executing, run `yarn start`

**Comment by im-coder-lg** [comment]
That seems to work. But now, I think I might've uncovered a bug. Nothing works. Is it due to development?

**Comment by sumeshir26** [comment]
@Melvin-Abraham 
![image](https://user-images.githubusercontent.com/68823982/144351594-a59d8131-361b-4d73-97da-388a49e81701.png)

**Comment by Melvin-Abraham** [comment]
> That seems to work. But now, I think I might've uncovered a bug. Nothing works. Is it due to development?

Can you elaborate and/or share some screenshot(s)?

**Comment by sumeshir26** [comment]
@Melvin-Abraham Once I build, it does not prompt me for the key file
Path nor does settings open. The suggestions do not work. The icon on the taskbar is the generic electron icon.
@im-coder-lg Are you facing the same issue?

**Comment by im-coder-lg** [comment]
Yup! That's the problem! I think it's due to development.

**Comment by Melvin-Abraham** [comment]
> Once I build, it does not prompt me for the key file path nor does settings open. The suggestions do not work. The icon on the taskbar is the generic electron icon.

@sumeshir26 @im-coder-lg That is expected for now since these features are yet to be implemented. These will be worked upon incrementally based on development on other parts like configuration, IPC, services, etc. in the main process.

**Comment by Melvin-Abraham** [comment]
I hope other than that, the build is working just fine for now?

**Comment by im-coder-lg** [comment]
Yup!
