### ISSUE TITLE
[🐛 Bug]: Personal Results

### ISSUE THREAD

**Issue by ThePrimeDev** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#784]
### What went wrong?

When getting personal results notification, on click pops up and dissapears the window, and i cant enable it.

### Steps to reproduce the bug

Try saying: What is my name

### App Version

v1.0.0

### OS Version

Ubuntu 20.04 LTS | Phone: Xiaomi 11 Lite 5G NE

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by cmt29** [comment]
This happened to me too, so following.

**Comment by im-coder-lg** [comment]
You checked Google Home notifs?

**Comment by cmt29** [comment]
Yes, the notification comes through OK, but when you either tap on it, or try to answer 'yes' a blank windows appears on my phone, then disappears.
Also, don't know if this is related, but when I go to Google Assistant settings on my phone -> Personal Results I'm met with "To turn on personal results, you'll first need to add a device in your Home app."

**Comment by ThePrimeDev** [comment]
> You checked Google Home notifs?

Yes. Im not that noob. If i click on the notify the window appears and instantly dissapears, and nothing happens.

**Comment by im-coder-lg** [comment]
I mean to say, did you open Google Home and go to the notification section?

**Comment by cmt29** [comment]
Yes, I've tried that, thanks.

**Comment by Xalriel** [comment]
I have the same issue here...
And I don't have a notification history in my Google Home App

**Comment by chaorace** [comment]
I'm encountering a similar issue. Tapping the notification toast takes me to an activity that instantly closes. I get the same result when I open Google Home notification history and tap on the associated item there.

I'm using a U.S. Samsung Z-Flip 3, model#: SM-F711U1. It is on Android 12/One UI 4.1.1 (September 1st 2022 security patch), Google Play (September 1st 2022 patch). I have Google Assistant (September 15th 2022 patch) and Google Home (September 30th 2022 patch) installed.

Here's what logcat shows when I tap the toast notification body:

```
10-19 11:48:32.971  2627  2627 E SubscreenNotificationInfoManager: isRemoveGroupSummnary : true
10-19 11:48:33.013  1488  2846 E WindowManager: win=Window{aeb3410 u0 NotificationShade} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=4 caller=com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3021 com.android.server.wm.WindowManagerService.relayoutWindow:2743 com.android.server.wm.Session.relayout:242 android.view.IWindowSession$Stub.onTransact:800 com.android.server.wm.Session.onTransact:177 android.os.Binder.execTransactInternal:1215 android.os.Binder.execTransact:1179 
10-19 11:48:33.088  5535  5535 E ASAPeer : Failed to show Settings fragment
10-19 11:48:33.088  5535  5535 E ASAPeer : android.view.InflateException: Binary XML file line #22: Error inflating class (not found)com.google.android.apps.gsa.assistant.settings.devices.shared.PersonalInfoScreenfulSwitchPreference
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at androidx.preference.aq.d(PG:9)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at androidx.preference.aq.b(PG:13)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at androidx.preference.aq.b(PG:15)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at androidx.preference.aq.b(PG:15)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at androidx.preference.aq.a(PG:6)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at androidx.preference.au.f(PG:6)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at com.google.android.apps.gsa.assistant.settings.base.AssistantSettingsPreferenceFragmentBase.ga(PG:3)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at androidx.preference.ai.onCreate(PG:8)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at com.google.android.apps.gsa.assistant.settings.base.AssistantSettingsPreferenceFragmentBase.onCreate(PG:1)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at com.google.android.apps.gsa.assistant.settings.devices.assistantsdk.DeviceIdAssistantSDKSettingsFragment.onCreate(PG:4)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at android.support.v4.app.Fragment.performCreate(PG:4)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at android.support.v4.app.ca.e(PG:152)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at android.support.v4.app.FragmentManager.av(PG:112)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at android.support.v4.app.FragmentManager.ax(PG:10)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at android.support.v4.app.FragmentManager.an(PG:8)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at android.support.v4.app.FragmentManager.ah(PG:1)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at com.google.android.apps.gsa.assistant.settings.f.gn(PG:35)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at com.google.apps.tiktok.tracing.er.gn(PG:3)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at com.google.common.util.concurrent.cc.run(PG:7)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at android.os.Handler.handleCallback(Handler.java:938)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at android.os.Looper.loopOnce(Looper.java:226)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at android.os.Looper.loop(Looper.java:313)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at android.app.ActivityThread.main(ActivityThread.java:8855)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at java.lang.reflect.Method.invoke(Native Method)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
10-19 11:48:33.088  5535  5535 E ASAPeer : Caused by: java.lang.ClassNotFoundException: com.google.android.apps.gsa.assistant.settings.devices.shared.PersonalInfoScreenfulSwitchPreference
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at java.lang.Class.classForName(Native Method)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at java.lang.Class.forName(Class.java:454)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at androidx.preference.aq.c(PG:8)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	at androidx.preference.aq.d(PG:3)
10-19 11:48:33.088  5535  5535 E ASAPeer : 	... 26 more
10-19 11:48:33.088  5535  5535 E ASAPeer : Caused by: java.lang.ClassNotFoundException: com.google.android.apps.gsa.assistant.settings.devices.shared.PersonalInfoScreenfulSwitchPreference
10-19 11:48:33.088  5535  5535 E ASAPeer : 	... 30 more
10-19 11:48:33.091  1488  1885 E WindowManager: win=Window{750f021 u0 com.google.android.googlequicksearchbox/com.google.android.apps.gsa.shared.util.permissions.ProxyActivity EXITING} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=4 caller=com.android.server.wm.ActivityRecord.destroySurfaces:6256 com.android.server.wm.ActivityRecord.destroySurfaces:6237 com.android.server.wm.WindowState.onExitAnimationDone:6089 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda15.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.Task.lambda$onAnimationFinished$34:8283 com.android.server.wm.Task$$ExternalSyntheticLambda33.accept:2 
10-19 11:48:33.101  4008  4008 E pageboostd: Received HALT command code 2
10-19 11:48:33.182  5120  5139 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:593 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack> 
10-19 11:48:33.182  2627  2883 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:593 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack> 
10-19 11:48:33.183  2627  2678 E TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:593 android.os.Binder.execTransactInternal:1220 android.os.Binder.execTransact:1179 <bottom of call stack> 
10-19 11:48:33.628  2627 16990 E PowerUI.Notification: no saved value, so we do nothing !!
```

**Comment by im-coder-lg** [comment]
Looks like the request is created but is valueless, hence it is omitted..

**Comment by GreenDragon527** [comment]
Would having other devices added in the Google Home app solve this? I'm encountering the same issue, but I noticed there was a dummy device that represented the client in the list of home apps. Does one need to have a regular device added to Google Home first for the client to show up?

**Comment by chaorace** [comment]
> Would having other devices added in the Google Home app solve this? I'm encountering the same issue, but I noticed there was a dummy device that represented the client in the list of home apps. Does one need to have a regular device added to Google Home first for the client to show up?

I have plenty of devices in Google Home and the issue still affects me

**Comment by milan-tom** [comment]
> You need to set up the credentials as a desktop app **NOT** a web client. Also make sure you enable account linking via Google in your Action.

This solution worked for me.

**Comment by GreenDragon527** [comment]
How did you manage it @milan-tom ?

**Comment by milan-tom** [comment]
> Also make sure you enable account linking via Google in your Action.

Firstly, I followed the above instruction via the Google Actions Console.

Then, I downloaded my credentials JSON file from the desktop app download link (seen two rows above the download button you are instructed to click in the image from the setup guide below):

![](https://raw.githubusercontent.com/wiki/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/assets/cred-download.png)

After doing this, it was simply a case of replacing the credentials file passed into the Google Assistant application before with the desktop app credentials and relaunching the assistant. Then, I just followed these [instructions to enable personal results](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#enabling-personal-results-optional), and I was done.

**Comment by GreenDragon527** [comment]
![image](https://user-images.githubusercontent.com/40502690/210462989-902de4d0-62bb-4cb8-845a-fcdf53b97b9e.png)
Do I need to do Google Sign In and OAuth? Or should Google Sign In alone have worked?

When I tried to download my JSON the app tells me it has an error due to being unauthourised.

**Comment by GreenDragon527** [comment]
Ok nvm, I had forgotten to delete the old tokens file. My bad, works great! Thanks @milan-tom and @androidacy-user !

**Comment by anthonyg2003** [comment]
Can someone explain the Account Linking setup? Which are the correct choices for Linking Type? Even Implicit Type requires a Authorization URL, what would that be? @GreenDragon527, what did you figure out?

![image](https://user-images.githubusercontent.com/19936471/222760725-d5e9425f-c6bc-4123-9ecf-de3b405432c0.png)

**Comment by sumeshir26** [comment]
@anthonyg2003 Try deleting the old token file

**Comment by ZeekWorld** [comment]
I still can't enable personal results.
Followed all the steps, download the "Desktop" OAuth and still no go.
Any help would be awesome.
Enabled account linking, not sure if I need more than the screenshot
![image](https://user-images.githubusercontent.com/16088952/224118299-4ac1b6b3-28aa-4154-9c8d-44e826c4563f.png)

**Comment by SebHex** [comment]
None of the suggested solutions worked for me, I tried:

1. Ensuring I followed the [setup guide](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client) correctly
2. Using [desktop credentials](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/784#issuecomment-1370355169)
3. Enabling [account linking](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/53#issuecomment-875133184)

However, I was able to resolve the issue by using an Android emulator to receive the notification on an Android 12 device, instead of my current Android 9 device

Here's the steps I followed:

1. [Set up an Android emulator](https://developer.android.com/about/versions/12/get#on_emulator)
2. Install the [Google Home](https://play.google.com/store/apps/details?id=com.google.android.apps.chromecast.app) app on the emulated Android
3. Open the app and sign into your Google account when prompted
4. Follow the [enabling personal results guide](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#enabling-personal-results-optional) and open the notification on the emulated Android

![image](https://user-images.githubusercontent.com/86801115/224526139-d3f988ec-6df1-4c45-9d74-edbb6597a13c.png)

**Comment by lucasdeeiroz** [comment]
> None of the suggested solutions worked for me, I tried:
> 
> 1. Ensuring I followed the [setup guide](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client) correctly
> 2. Using [desktop credentials](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/784#issuecomment-1370355169)
> 3. Enabling [account linking](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/53#issuecomment-875133184)
> 
> However, I was able to resolve the issue by using an Android emulator to receive the notification on an Android 12 device, instead of my current Android 9 device
> 
> Here's the steps I followed:
> 
> 1. [Set up an Android emulator](https://developer.android.com/about/versions/12/get#on_emulator)
> 2. Install the [Google Home](https://play.google.com/store/apps/details?id=com.google.android.apps.chromecast.app) app on the emulated Android
> 3. Open the app and sign into your Google account when prompted
> 4. Follow the [enabling personal results guide](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#enabling-personal-results-optional) and open the notification on the emulated Android
> 
> ![image](https://user-images.githubusercontent.com/86801115/224526139-d3f988ec-6df1-4c45-9d74-edbb6597a13c.png)

Thank you! Emulator was the way to go for me, physical devices didn't work.

**Comment by ftk789** [comment]
If it still didn't work for anyone, It's Solved in https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/863#issuecomment-1474980944

**Comment by Joel-CA** [comment]
> None of the suggested solutions worked for me, I tried:
> 
> 1. Ensuring I followed the [setup guide](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client) correctly
> 2. Using [desktop credentials](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/784#issuecomment-1370355169)
> 3. Enabling [account linking](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/53#issuecomment-875133184)
> 
> However, I was able to resolve the issue by using an Android emulator to receive the notification on an Android 12 device, instead of my current Android 9 device
> 
> Here's the steps I followed:
> 
> 1. [Set up an Android emulator](https://developer.android.com/about/versions/12/get#on_emulator)
> 2. Install the [Google Home](https://play.google.com/store/apps/details?id=com.google.android.apps.chromecast.app) app on the emulated Android
> 3. Open the app and sign into your Google account when prompted
> 4. Follow the [enabling personal results guide](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#enabling-personal-results-optional) and open the notification on the emulated Android
> 
> ![image](https://user-images.githubusercontent.com/86801115/224526139-d3f988ec-6df1-4c45-9d74-edbb6597a13c.png)

I'm trying out this virtual machine solution because as soon as I click on the notification it crashes as others have described; however, going through the personal results guide, I'm not getting the notification to my virtual machine at all (just to my actual mobile device like before). Is there something you did to switch which device receives the notification? I have indeed installed Google Home, Google Assistant, and the Google app to my virtual machine as described in the instructions.
